// <auto-generated />
using GolfProductApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace GolfProductApi.Migrations
{
    [DbContext(typeof(GolfProductDbContext))]
    [Migration("20180528161138_GolfProductDbInitialMigration")]
    partial class GolfProductDbInitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GolfProductApi.Entities.Catalog", b =>
                {
                    b.Property<short>("CatalogId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("CatalogId");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasName("uidx_Catalog_Description");

                    b.ToTable("Catalogs");
                });

            modelBuilder.Entity("GolfProductApi.Entities.CatalogCategory", b =>
                {
                    b.Property<short>("CatalogId");

                    b.Property<short>("CategoryId");

                    b.HasKey("CatalogId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogCategory");
                });

            modelBuilder.Entity("GolfProductApi.Entities.Category", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("CategoryId");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasName("uidx_Category_Description");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("GolfProductApi.Entities.CatalogCategory", b =>
                {
                    b.HasOne("GolfProductApi.Entities.Catalog", "Catalog")
                        .WithMany("CatalogCategories")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GolfProductApi.Entities.Category", "Category")
                        .WithMany("CatalogCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
