// <auto-generated />
using GolfProductApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GolfProductApi.Migrations
{
    [DbContext(typeof(GolfProductDbContext))]
    [Migration("20180528172849_GolfProductDbAddSeedDataForCatalog_Category_Family")]
    partial class GolfProductDbAddSeedDataForCatalog_Category_Family
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GolfProductApi.Entities.Catalog", b =>
                {
                    b.Property<short>("CatalogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("CatalogId");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasName("uidx_Catalog_Description");

                    b.ToTable("Catalogs");

                    b.HasData(
                        new { CatalogId = (short)1, Description = "US Catalog" },
                        new { CatalogId = (short)2, Description = "Japan Catalog" }
                    );
                });

            modelBuilder.Entity("GolfProductApi.Entities.CatalogCategory", b =>
                {
                    b.Property<short>("CatalogId");

                    b.Property<short>("CategoryId");

                    b.HasKey("CatalogId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("CatalogCategory");

                    b.HasData(
                        new { CatalogId = (short)1, CategoryId = (short)1 },
                        new { CatalogId = (short)1, CategoryId = (short)2 },
                        new { CatalogId = (short)1, CategoryId = (short)3 },
                        new { CatalogId = (short)2, CategoryId = (short)1 },
                        new { CatalogId = (short)2, CategoryId = (short)2 }
                    );
                });

            modelBuilder.Entity("GolfProductApi.Entities.Category", b =>
                {
                    b.Property<short>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("CategoryId");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasName("uidx_Category_Description");

                    b.ToTable("Category");

                    b.HasData(
                        new { CategoryId = (short)1, Description = "Woods" },
                        new { CategoryId = (short)2, Description = "Irons" },
                        new { CategoryId = (short)3, Description = "Putters" }
                    );
                });

            modelBuilder.Entity("GolfProductApi.Entities.Family", b =>
                {
                    b.Property<int>("FamilyId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<short>("CategoryId");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.HasKey("FamilyId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasName("uidx_Family_Description");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("GolfProductApi.Entities.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(250);

                    b.Property<int>("FamilyId");

                    b.Property<byte>("Gender");

                    b.Property<byte>("Hand");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(18);

                    b.HasKey("ProductId");

                    b.HasIndex("Description")
                        .IsUnique()
                        .HasName("uidx_Product_Sku");

                    b.HasIndex("FamilyId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("GolfProductApi.Entities.CatalogCategory", b =>
                {
                    b.HasOne("GolfProductApi.Entities.Catalog", "Catalog")
                        .WithMany("CatalogCategories")
                        .HasForeignKey("CatalogId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GolfProductApi.Entities.Category", "Category")
                        .WithMany("CatalogCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GolfProductApi.Entities.Family", b =>
                {
                    b.HasOne("GolfProductApi.Entities.Category", "Category")
                        .WithMany("Families")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GolfProductApi.Entities.Product", b =>
                {
                    b.HasOne("GolfProductApi.Entities.Family", "Family")
                        .WithMany("Products")
                        .HasForeignKey("FamilyId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
